export const HOST_LINK = 'https://mycinemalistback-production.up.railway.app'
export const HOST_LINK_IMAGE = 'https://image.tmdb.org/t/p/w500'
export const MAIN_PAGE_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PROFILE_ROUTE = '/profile'
